import { NextResponse } from 'next/server';
import { Mistral } from '@mistralai/mistralai';
import { REED_BREED_KNOWLEDGE_BASE } from '@/lib/knowledge-base';

// Initialize the Mistral client
// Note: In production, ensure MISTRAL_API_KEY is set in your environment variables.
const apiKey = process.env.MISTRAL_API_KEY || '';
const client = new Mistral({ apiKey: apiKey });

export async function POST(req: Request) {
  try {
    if (!apiKey) {
      return NextResponse.json(
        { error: 'Mistral API key not configured on server.' },
        { status: 500 }
      );
    }

    const { messages } = await req.json();

    if (!messages || !Array.isArray(messages)) {
      return NextResponse.json(
        { error: 'Invalid message format.' },
        { status: 400 }
      );
    }

    // Call the Mistral API
    const chatResponse = await client.chat.complete({
      model: 'mistral-tiny',
      messages: [
        {
          role: 'system',
          content: `${REED_BREED_KNOWLEDGE_BASE}`
        },
        ...messages
      ],
    });

    const reply = chatResponse.choices?.[0]?.message?.content;

    if (!reply) {
      throw new Error('No response generated by Mistral.');
    }

    return NextResponse.json({ reply });
  } catch (error: unknown) {
    console.error('Mistral API Error:', error);
    const errorMessage = error instanceof Error ? error.message : 'An error occurred during the chat request.';
    return NextResponse.json(
      { error: errorMessage },
      { status: 500 }
    );
  }
}
